# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test RFC counting (including download)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get install zsh
    - name: Parse for organizations and domains
      run: |
        cd rfccounter
        zsh parse_rfc.sh
    - name: Upload parse results
      uses: actions/upload-artifact@v2
      with:
        name: Upload tables
        path: rfccounter/*.txt
    - name: Count RFCs and content
      run: |
        cd rfccounter
        zsh count_rfc.sh
    - name: Upload count results
      uses: actions/upload-artifact@v2
      with:
        name: Upload tables
        path: rfccounter/rfc_word_lines.txt
